apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: build-sophia-litellm
  namespace: sophia-core
spec:
  source:
    type: Git
    git:
      uri: http://forgejo-svc.sophia-git.svc:3000/cyclopdev/sophia-brain.git
    sourceSecret:
      name: forgejo-creds
    # Assure-toi que ce chemin correspond à l'emplacement de ton Containerfile
    contextDir: config/okd/core/litellm
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: sophia-litellm:latest
