FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

RUN microdnf install -y \
    shadow-utils \
    tar \
    gzip \
    ca-certificates \
    libstdc++ \
    && microdnf clean all

RUN useradd -u ${APP_UID:-1001} -g 0 -m -s /bin/bash ${APP_USER:-app-user}
USER ${APP_UID:-1001}
WORKDIR /home/${APP_USER:-app-user}

RUN curl -fsSL https://pixi.sh/install.sh | bash
ENV PATH="/home/${APP_USER:-app-user}/.pixi/bin:${PATH}"

CMD ["/bin/bash"]
