apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sophia-postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # Doit être vide pour matcher une PVC sans classe
  local:
    path: /var/lib/sophia/postgres-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master-0 # Vérifie ton hostname avec 'oc get nodes'
