apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-litellm
  namespace: sophia-core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Ajuste la taille selon tes besoins (10Go suffisent pour Postgres)
